### ISSUE TITLE
Code Reuse

### ISSUE THREAD

**Issue by Aerodlyn** [GY1970/capstone#1]
https://github.com/GY1970/capstone/blob/60bd6f0c18b1e75b89a6d867f2ce742144347a05/resources/css/style.css#L25-L43

You can combine tags that use the same properties by writing something similar to `name1, name2 { ... }`. This allows you to keep common properties for similar elements together, and will make it much easier to update in the future.

**Comment by GY1970** [comment]
great suggestion.  thank you very much.
