### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [GY1970/capstone#2]
You definitely had the right idea about the way you were supposed to structure your site, but it could definitely be improved. Your site looks relatively fine at the resolution of my monitor, but once I start to lower the window size, it sorta falls apart. For example, the image of the man reading starts to get distorted really aggressively as the window gets smaller. I believe that the best approach for solving these layout and scale issues would be to look into the different ways you can display an element, particularly the flex type of display (i.e. `display: flex;`). Using grid columns is what looks like the primary cause of the layout and scaling issues.

**Comment by GY1970** [comment]
i really struggled with the whole layout & positioning topics.  i felt pressured to meet the deadline, but sort of knew the approach to any project/problem was to break it down to smaller, more manageable problems... i guessed i felt overwhelmed.  but with time, hopefully, i can improve on it and continue to learn and grow.  thank you so much for your time and advice.
